config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    # 瀏覽所有餐廳的最新動態
    collection do
      get :feeds
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard

      post :favorite
      post :unfavorite

      post :like
      post :unlike
    end
  end
  
  resources :users, only: [:index, :show, :edit, :update]

  resources :followships, only: [:create, :destroy]


  resources :categories, only: :show
  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name

  has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/followship.rb
class Followship < ApplicationRecord
  validates :following_id, uniqueness: { scope: :user_id }
  
  belongs_to :user
  belongs_to :following, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  mount_uploader :image, PhotoUploader
  validates_presence_of :name
  belongs_to :category, optional: true
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
  

  has_many :comments, dependent: :restrict_with_error       
  has_many :restaurants, through: :comments
  

  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user
  
  mount_uploader :avatar, AvatarUploader

  def admin?
    self.role == "admin"
  end
  
   def following?(user)
    self.followings.include?(user)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin

  private

    def authenticate_admin
      unless current_user.admin?
        flash[:alert] = "Not allow!"
        redirect_to root_path
      end
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/followships_controller.rb
class FollowshipsController < ApplicationController
  def create
    @followship = current_user.followships.build(following_id: params[:following_id])

    if @followship.save
      flash[:notice] = "Successfully followed"
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = @followship.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @followship = current_user.followships.where(following_id: params[:id]).first
    @followship.destroy
    flash[:alert] = "Followship destroyed"
    redirect_back(fallback_location: root_path)
  end
 
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end
  
  def show
  @restaurant = Restaurant.find(params[:id])
  @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    @restaurant.likes.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unlike
    @restaurant = Restaurant.find(params[:id])
    likes = Like.where(restaurant: @restaurant, user: current_user)
    likes.destroy_all
    redirect_back(fallback_location: root_path)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update] 


  def show
    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings
    @followers = @user.followers 
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)  
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user) 
  end

  def index
    @users = User.all
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <% if @user.errors.any? %>
      <h2>We have some errors here !</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <hr>
    <% end %>
    <H1>Edit Profile</H1>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control"  %>
        </div>

        <div class="form-group">
          <%= f.label :intro, "Introduction" %>
          <%= f.text_field :intro, class: "form-control" %>
        </div>        

        <div class="form-group">
          <%= f.label :avatar, "大頭照上傳" %>
          <%= image_tag @user.avatar if @user.avatar? %>
          <%= f.file_field :avatar %>
        </div>

        <div class="form-group">
          <%= f.submit "Update", class: "btn btn-primary" %>
          <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>

        </div>
      <% end %>    
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

      <ul class="nav nav-tabs">
      <li role="presentation" >
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presentation">
        <%= link_to '最新動態', feeds_restaurants_path %>
      </li>
      
      <li role="presentation" class="active">
        <%= link_to '美食達人', users_path %>
      </li>

    </ul>

  </div>
</div>

<br>

<div class="container">
  <div class="row">

    <div class="col-md-12">
      <div class="page-header">
        <h1>美食達人</h1>
      </div>
    </div>

    <% @users.each do |user| %>
      <div class="col-md-1 col-sm-2 col-xs-6 text-center user-item">

        <%= link_to user_path(user) do %>
        
          <img src="http://via.placeholder.com/80x80" class="img-rounded">
          <p><%= user.name %></p>
        <% end %>

        <%= render partial: "shared/follow", locals: {user: user} %>

      </div>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      
      <div class = "col-md-3 col-sm-4">
        <%= image_tag @user.avatar, class: "img-responsive img-rounded" %>          
      </div>
      


      <div class="col-md-9 col-sm-8">
        <h1><%= @user.name %></h1>  
        <p><%= @user.email %></p>
        <p><%= @user.intro %></p>
        <% if @user.email == current_user.email %>
          <%=link_to 'Edit Profile', edit_user_path, class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="clearfix"></div>

      <hr>
      <h3>已評論<%= @commented_restaurants.count %>間餐廳</h3>
        <div>
          <% @commented_restaurants.each do |restaurant| %>
            <div class="col-md-1 col-sm-2 text-center user-item">
              <%= link_to restaurant_path(restaurant) do %>
                <div class="my-restaurant">
                  <div class="my-restaurant-img">
                    <% if restaurant.image? %>
                      <%= image_tag restaurant.image, class: "img-responsive img-rounded" %>
                    <% else %>
                      <img src="http://via.placeholder.com/50x50" class="img-responsive img-rounded">
                    <% end %>                    
                  </div>
                  <div>
                    <%= restaurant.name %>
                  
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>