config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    # 瀏覽所有餐廳的最新動態
    collection do
      get :feeds
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard

      post :favorite
      post :unfavorite

      post :like
      post :unlike
    end
  end
  
  resources :users, only: [:index, :show, :edit, :update]

  resources :followships, only: [:create, :destroy]


  resources :categories, only: :show
  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  mount_uploader :image, PhotoUploader
  validates_presence_of :name
  belongs_to :category, optional: true
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  
  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to create"
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "restaurant was successfully updated"
      redirect_to admin_restaurant_path(@restaurant)
    else
      flash.now[:alert] = "restaurant was failed to update"
      render :edit
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "restaurant was deleted"
  end


  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end
  
  def show
  @restaurant = Restaurant.find(params[:id])
  @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    @restaurant.likes.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unlike
    @restaurant = Restaurant.find(params[:id])
    likes = Like.where(restaurant: @restaurant, user: current_user)
    likes.destroy_all
    redirect_back(fallback_location: root_path)
  end


end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %>'s Dashboard</h1>
      <hr>
      <ul>
        <li>有 <%= @restaurant.comments.count %> 筆評論</li>
        <li>這家餐廳的平均價位為 $XXX</li>
        <li>有 XX 人收藏這家餐廳</li>
      </ul>
    </div>
  </div>
</div>  

app/views/restaurants/feeds.html.erb
<div class="container">
  <div class="row">
  
    <ul class="nav nav-tabs">
      <li role="presentation">
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presentation" class="active">
        <%= link_to '最新動態', feeds_restaurants_path %>
      </li>
      <li role="presentation">
        <%= link_to '美食達人', users_path %>
      </li>

    </ul>

  </div>
</div>

<div class="container">
  <div class="row">

    <div class="col-md-10 col-md-offset-1">
      <h1>餐廳最新動態</h1>
      <hr>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">最新餐廳</div>
          <div class="panel-body">
            <% @recent_restaurants.each do |restaurant| %>
              <div>
                <h4>
                  <%= link_to restaurant.name, restaurant_path(restaurant) %>
                  <small><%= restaurant.category.name %></small>
                </h4>
                <p><%= truncate(restaurant.description, length: 80) %></p>
                <hr>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">最新評論</div>
          <div class="panel-body">
            <% @recent_comments.each do |comment| %>
              <div>
                <h4>
                  <%= link_to comment.restaurant.name, restaurant_path(comment.restaurant) %>
                </h4>
                <p><%= truncate(comment.content, length: 80) %><small > - by <%= link_to comment.user.name, user_path(comment.user) %></small></p>
                <hr>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">

      <ul class="nav nav-tabs">
      <li role="presentation" class="active">
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presentation">
        <%= link_to '最新動態', feeds_restaurants_path %>
      </li>
      
      <li role="presentation">
        <%= link_to '美食達人', users_path %>
      </li>

    </ul>

  </div>
</div>

<br>




<div class="container">
  <div class="row">
    <ul class="nav nav-pills nav-pills-center">
      <li role="presentation" class="active"><%= link_to "全部餐廳", root_path %></li>
      <% @categories.each do |category| %>
        <li role="presentation"><%= link_to category.name, category_path(category) %></li>
      <% end %>
    </ul>

    </br>

    <%= render partial: "shared/restaurant_list" %>
    
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>  
    </div>
    
    <div class="col-md-4">
      <%= image_tag @restaurant.image, class: "img-responsive center-block" %> <br>
      <div class="well">
        <ul class="list-unstyled">
          <li>Restaurant Category:<%= @restaurant.category.name %></li>
          <li>Opening Hours:<%= @restaurant.opening_hours %></li>
          <li>Tel: <%= @restaurant.tel %></li>
          <li>Address: <%= @restaurant.address %></li>  
        </ul>        
      </div>      
    </div>

    <div class="col-md-8">
      <%= simple_format @restaurant.description %>
      <hr>
      <%= link_to 'Dashboard', dashboard_restaurant_path(@restaurant), class: "btn btn-primary" %>
      <%= render partial: "shared/favorite", locals: {restaurant: @restaurant} %>
      <%= render partial: "shared/like", locals: {restaurant: @restaurant} %>
    </div>
    <div class="clearfix"></div>
    <%= link_to 'Back to index', restaurants_path %>
    <hr>
  </div>  
</div>

<div class="container">
  <div class="row">
    <% @restaurant.comments.each do |comment| %>
      <div>
        <h4><%= comment.user.email.split("@")[0] %></h4>
        <p><%= simple_format comment.content %></p>
        <p class="text-muted">
          <em><%= time_ago_in_words(comment.created_at) %> ago </em>
        </p>
        <% if current_user.admin? %>
        <%= link_to "Delete", restaurant_comment_path(@restaurant, comment), method: :delete, data: {confirm:"Are you sure?"} %>
        <% end %>
      </div>
      <hr>      
    <% end %>

   <%= form_for [@restaurant, @comment] do |f| %>
    <div class="form-group">
      <%= f.text_area :content, placeholder: "留個言吧", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
      <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
    </div>
  <% end %>

  
  </div>
</div>